const types = {
  SET_ARTICLE_LIST: 'tag/SET_ARTICLE_LIST',
  SET_ARTICLE_TOTAL: 'tag/SET_ARTICLE_TOTAL',
  SET_CURRENT_PAGE: 'tag/SET_CURRENT_PAGE',
  SET_TAG_NAME: 'SET_TAG_NAME'
}

export default types
