const types = {
  SET_ONE_RANDOM_ARTICLE: 'side/SET_ONE_RANDOM_ARTICLE',
  SET_RECOMMEND_ARTICLE: 'side/SET_RECOMMEND_ARTICLE',
  SET_POLYMERIZATION_ARTICLE: 'side/SET_POLYMERIZATION_ARTICLE'
}

export default types
