const types = {
  SET_ONE_RANDOM_ARTICLE: 'SET_ONE_RANDOM_ARTICLE',
  SET_RECOMMEND_ARTICLE: 'SET_RECOMMEND_ARTICLE',
  SET_POLYMERIZATION_ARTICLE: 'SET_POLYMERIZATION_ARTICLE'
}

export default types
